### ISSUE TITLE
Inconsistencies in Use of Tokens on Labs in Syllabus 

### ISSUE THREAD

**Issue by Colebeep** [CICS110/CICS110.github.io#105]
The second bolded header for the section reads as follows:
"**What can tokens be used for?**

Tokens can be used on the following assessments:
        Homework
        Labs
"

at the end of the section:

"**Tokens may not be used or gained on in-class exercises or labs.**"

**Comment by bburns-ds** [comment]
Policy that was decided on:
1. Submissions before or on due date earn token +1, existing policy of -1 token per day mitigated
2. The submission that students activate on gradescope is the submission we use. If their active submission is after the due date, and they didn't report that they want to use tokens, we apply the late policy of -1 to the max grade per late day. Students have to report when they want to use tokens
3. You can earn tokens from only homeworks
4. You can apply tokens to labs and homeworks

**Comment by bburns-ds** [comment]
IMPORTANT: Need to clarify somehow that only "quality" submissions can earn a token, and not just any early submission, if not already specified.
