### ISSUE TITLE
grading scale update/consistency fix

### ISSUE THREAD

**Issue by bburns-ds** [CICS110/CICS110.github.io#117]
The percent grading scale needs to be either removed or clarified (what is the mapping), and there are inconsistencies on if the scale is 0-4 or 1-5 in the syllabus, i.e https://cics110.github.io/main/information/syllabus#grading-categories

**Comment by bburns-ds** [comment]
Also, need to clarify quiz grading, maybe a Tim thing

**Comment by jdyeager** [comment]
I just pushed a "grading" branch with proposed edits. I want someone to look over that before we merge it.

This does not include grading quizzes information, because I don't really know how we're doing that. Especially given people have already taken a quiz maybe having a different mental paradigm.

**Comment by bburns-ds** [comment]
I'd catch grading up to main, make a pull request into main, and then attach tim as a reviewer. It looks good to me though

**Comment by jdyeager** [comment]
I have no idea how to do the catching up except when PRing, and don't know how to attach a review. So I will do that once the HW 1 and Lecture 3 stuff is more under control.

**Comment by bburns-ds** [comment]
I think pring main into grading is the only way. To attach a review to the new pull request, you want to click the "Reviewers" section at the top of the sidebar:
<img width="1274" alt="Screen Shot 2023-02-14 at 1 16 02 PM" src="https://user-images.githubusercontent.com/72670119/218823081-560220b9-74f2-4f92-a3d7-c8067dbeeace.png">

**Comment by timdrichards** [comment]
@jdyeager this looks good to me. I would merge in changes on main into your branch, then create a PR for this.

**Comment by jdyeager** [comment]
Alrighty, PR-ed and brought into canonical timeline.
